spring:
  application:
    name: BankAccountService
  datasource:
    url: jdbc:postgresql://localhost:5438/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        default_schema: bankservice

server:
  port: 8089
  servlet:
    context-path: /bank-account-service

person-service:
  client:
    url: http://localhost:8088/person-service