spring:
  application:
    name: BankAccountService
  datasource:
    url: jdbc:postgresql://localhost:5438/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: backservice
server:
  port: 8088
  servlet:
    context-path: /bank-account-service
